name: Test

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2022.02.09'

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - uses: actions/checkout@v1

      - name: Cache dependencies lint
        run: echo "$(clj-kondo --lint \"$(clojure -Spath -A:provided)\") --parallel"

      - name: Run linter
        run: clj-kondo --lint src test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.2.1
        with:
          babashka-version: 1.0.168

      - uses: actions/checkout@v1

#      - run: bb run format-check
      - run: bb -m tasks/cljstyle "check" "src" "test"

  test-clj:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

#      - name: Setup Babashka
#        uses: turtlequeue/setup-babashka@v1.2.1
#        with:
#          babashka-version: 0.3.1

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

#      - run: bb run test
      - run: PATHOM_TEST=true clojure -A:provided:test:test-deps

  test-cljs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: '1.10.1.469'

      - name: Cache maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}
          restore-keys: |
            m2-

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node_modules-

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: NPM Install
        run: npm install

      - name: Compile CLJS tests
        run: npx shadow-cljs compile ci

      - name: Run CLJS tests
        run: npx karma start --single-run
